<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
	  <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
	  <Version>16.0.0-rc1</Version>
	  <Authors>Mario Lopez</Authors>
	  <Description>Highly configurable icon picker for Umbraco. 
With Iconic you will be able to create a property editor that can use virtually any font package out there and not only that, you will be able to select your icon from more than one package on the same property.
</Description>
	  <Copyright>Copyright © Mario Lopez</Copyright>
	  <Product>$(AssemblyName) - Core DLL</Product>
	  <PackageLicenseExpression>MIT</PackageLicenseExpression>
	  <PackageProjectUrl>https://github.com/Skartknet/Iconic</PackageProjectUrl>
	  <PackageIcon>icon.png</PackageIcon>
	  <PackageTags>umbraco plugin package icon picker editor backoffice</PackageTags>
	  <NeutralLanguage>en-US</NeutralLanguage>
	  <PackageReadmeFile>README.md</PackageReadmeFile>
	  <PackageIcon>iconic_logo.png</PackageIcon>	  
  </PropertyGroup>
	
	<ItemGroup>
	  <Compile Remove="IconicPackagesConfigurationEditor.cs" />
	  <Compile Remove="IconicPropertyEditor.cs" />
	</ItemGroup>
	

	<ItemGroup>
		<None Include="..\iconic_logo.png">
			<Pack>True</Pack>
			<PackagePath></PackagePath>
		</None>
		<None Include="..\README.md">
			<Pack>True</Pack>
			<PackagePath></PackagePath>
		</None>
	</ItemGroup>
	

	<ItemGroup>
	  <PackageReference Include="Microsoft.AspNetCore.Html.Abstractions" Version="2.2.0" />
	  <PackageReference Include="Microsoft.AspNetCore.Mvc.ViewFeatures" Version="2.2.0" />
	  <PackageReference Include="Umbraco.Cms.Core" Version="16.0.0" />
	</ItemGroup>


</Project>
