<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	<StaticWebAssetBasePath>/</StaticWebAssetBasePath>
	<ContentTargetFolders>.</ContentTargetFolders>
	<Description>
		Highly configurable icon picker for Umbraco.
		With Iconic you will be able to create a property editor that can use virtually any font package out there and not only that, you will be able to select your icon from more than one package on the same property.
	</Description>
	<Product>$(AssemblyName)</Product>
	<PackageTags>umbraco plugin package icon picker editor backoffice umbraco-marketplace</PackageTags>
	<Version>14.0.0-beta1</Version>
	<Authors>Mario Lopez</Authors>
	<PackageProjectUrl>https://github.com/Skartknet/Iconic</PackageProjectUrl>
	<PackageIcon>iconic_logo.png</PackageIcon>
	<PackageReadmeFile>README.md</PackageReadmeFile>
	<RepositoryUrl>https://github.com/Skartknet/Iconic</RepositoryUrl>
	<PackageReleaseNotes></PackageReleaseNotes>
	<GeneratePackageOnBuild>False</GeneratePackageOnBuild>
	<PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>



  <ItemGroup>
    <None Remove="public\lang\en-US.xml" />
    <None Remove="public\lang\es-ES.xml" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="public\lang\en-US.xml">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </Content>
    <Content Include="public\lang\es-ES.xml">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

	<ItemGroup>
		<None Include="..\iconic_logo.png">
			<Pack>True</Pack>
			<PackagePath></PackagePath>
		</None>
		<None Include="..\README.nuget.md">
			<Pack>True</Pack>
			<PackagePath>README.md</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Umbraco.Cms.Core" Version="14.1.1" />
	</ItemGroup>
	
  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\Our.Iconic.Core\Our.Iconic.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="public\preconfigs.json">
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

</Project>
