<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	<StaticWebAssetBasePath>App_Plugins/Iconic</StaticWebAssetBasePath>
	<ContentTargetFolders>.</ContentTargetFolders>
	<Description>
		Highly configurable icon picker for Umbraco.
		With Iconic you will be able to create a property editor that can use virtually any font package out there and not only that, you will be able to select your icon from more than one package on the same property.
	</Description>
	<Product>$(AssemblyName)</Product>
	<PackageTags>umbraco plugin package icon picker editor backoffice umbraco-marketplace</PackageTags>
	<Version>6.0.0</Version>
	<Authors>Mario Lopez</Authors>
	<PackageProjectUrl>https://github.com/Skartknet/Iconic</PackageProjectUrl>
	<PackageIcon>iconic_logo.png</PackageIcon>
	<PackageReadmeFile>README.md</PackageReadmeFile>
	<RepositoryUrl>https://github.com/Skartknet/Iconic</RepositoryUrl>
	<PackageReleaseNotes></PackageReleaseNotes>
	<GeneratePackageOnBuild>False</GeneratePackageOnBuild>
	<PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="src\background.png" />
    <None Remove="src\js\build\findPolyfill.min.js" />
    <None Remove="src\js\src\iconic.controller.js" />
    <None Remove="src\js\src\iconic.dialog.controller.js" />
    <None Remove="src\js\src\iconic.directives.js" />
    <None Remove="src\js\src\iconic.models.js" />
    <None Remove="src\js\src\iconic.prevalues.controller.js" />
    <None Remove="src\js\src\iconic.prevalues.editor.controller.js" />
    <None Remove="src\lang\en-US.xml" />
    <None Remove="src\lang\es-ES.xml" />
    <None Remove="src\Styles\iconic.css" />
    <None Remove="src\Styles\iconic.min.css" />
    <None Remove="src\Styles\iconic.min.css.map" />
    <None Remove="src\Styles\iconic.scss" />
    <None Remove="src\Views\iconic.dialog.html" />
    <None Remove="src\Views\iconic.edit.dialog.html" />
    <None Remove="src\Views\iconic.html" />
    <None Remove="src\Views\iconic.prevalues.html" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="src\background.png">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Include="src\js\build\findPolyfill.min.js">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </Content>
    <Content Include="src\js\src\iconic.controller.js">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </Content>
    <Content Include="src\js\src\iconic.dialog.controller.js">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </Content>
    <Content Include="src\js\src\iconic.directives.js">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </Content>
    <Content Include="src\js\src\iconic.models.js">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </Content>
    <Content Include="src\js\src\iconic.prevalues.controller.js">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </Content>
    <Content Include="src\js\src\iconic.prevalues.editor.controller.js">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </Content>
    <Content Include="src\lang\en-US.xml">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </Content>
    <Content Include="src\lang\es-ES.xml">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </Content>
    <Content Include="src\Styles\iconic.css">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </Content>
    <Content Include="src\Styles\iconic.min.css">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </Content>
    <Content Include="src\Styles\iconic.min.css.map">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </Content>
    <Content Include="src\Styles\iconic.scss">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </Content>
    <Content Include="src\Views\iconic.dialog.html">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </Content>
    <Content Include="src\Views\iconic.edit.dialog.html">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </Content>
    <Content Include="src\Views\iconic.html">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </Content>
    <Content Include="src\Views\iconic.prevalues.html">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

	<ItemGroup>
		<None Include="..\iconic_logo.png">
			<Pack>True</Pack>
			<PackagePath></PackagePath>
		</None>
		<None Include="..\README.nuget.md">
			<Pack>True</Pack>
			<PackagePath>README.md</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Umbraco.Cms.Core" Version="14.0.0--preview002" />
	</ItemGroup>
	
  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net6.0'">
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="6.0.9" />
    <PackageReference Include="Umbraco.Cms.Core" Version="10.2.0" />
  </ItemGroup>
	 
  <ItemGroup Condition="'$(TargetFramework)' == 'net7.0'">
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="7.0.0" />
    <PackageReference Include="Umbraco.Cms.Core" Version="11.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Our.Iconic.Core\Our.Iconic.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="src\preconfigs.json">
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </Content>
    <Content Update="wwwroot\js\build\findPolyfill.min.js">
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </Content>
    <Content Update="wwwroot\js\src\iconic.controller.js">
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </Content>
    <Content Update="wwwroot\js\src\iconic.dialog.controller.js">
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </Content>
    <Content Update="wwwroot\js\src\iconic.directives.js">
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </Content>
    <Content Update="wwwroot\js\src\iconic.models.js">
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </Content>
    <Content Update="wwwroot\js\src\iconic.prevalues.controller.js">
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </Content>
    <Content Update="wwwroot\js\src\iconic.prevalues.editor.controller.js">
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </Content>
    <Content Update="wwwroot\lang\en-US.xml">
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </Content>
    <Content Update="wwwroot\lang\es-ES.xml">
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </Content>
    <Content Update="wwwroot\preconfigs.json">
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </Content>
    <Content Update="wwwroot\Styles\iconic.css">
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </Content>
    <Content Update="wwwroot\Styles\iconic.min.css">
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </Content>
    <Content Update="wwwroot\Styles\iconic.min.css.map">
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </Content>
    <Content Update="wwwroot\Styles\iconic.scss">
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </Content>
    <Content Update="wwwroot\Views\iconic.dialog.html">
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </Content>
    <Content Update="wwwroot\Views\iconic.edit.dialog.html">
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </Content>
    <Content Update="wwwroot\Views\iconic.html">
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </Content>
    <Content Update="wwwroot\Views\iconic.prevalues.html">
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </Content>
  </ItemGroup>
	<!-- Workaround for this bug (replace the analyzer name with the one you need to exclude (filename only, no extension) -->
	<Target Name="RemoveLuceneAnalyzer" BeforeTargets="CoreCompile">
		<ItemGroup>
			<Analyzer Remove="@(Analyzer)" Condition="%(FileName) == 'Lucene.Net.CodeAnalysis.CSharp'" />
		</ItemGroup>
	</Target>
</Project>
